[2024-06-05 18:43:35][INFO] Watching for file changes with StatReloader
[2024-06-05 18:43:46][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 18:47:45][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:48:41][INFO] Watching for file changes with StatReloader
[2024-06-05 18:48:46][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 18:49:18][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:49:18][INFO] Watching for file changes with StatReloader
[2024-06-05 18:49:27][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:49:27][INFO] Watching for file changes with StatReloader
[2024-06-05 18:49:35][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 18:52:39][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:52:40][INFO] Watching for file changes with StatReloader
[2024-06-05 18:52:55][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewsT/restEndpoint.py changed, reloading.
[2024-06-05 18:52:55][INFO] Watching for file changes with StatReloader
[2024-06-05 18:53:08][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 18:56:01][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:56:01][INFO] Watching for file changes with StatReloader
[2024-06-05 18:56:06][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 18:57:20][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 18:57:20][INFO] Watching for file changes with StatReloader
[2024-06-05 18:57:23][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:01:20][INFO] Watching for file changes with StatReloader
[2024-06-05 19:01:25][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:09:28][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 19:09:28][INFO] Watching for file changes with StatReloader
[2024-06-05 19:09:40][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 19:09:41][INFO] Watching for file changes with StatReloader
[2024-06-05 19:09:50][INFO] Watching for file changes with StatReloader
[2024-06-05 19:10:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 19:10:22][INFO] Watching for file changes with StatReloader
[2024-06-05 19:10:26][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:16:02][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 19:18:59][INFO] Watching for file changes with StatReloader
[2024-06-05 19:19:19][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:19:19][WARNING] Not Found: /favicon.ico
[2024-06-05 19:19:37][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:19:37][WARNING] Not Found: /favicon.ico
[2024-06-05 19:19:39][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:21:30][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-05 19:21:31][INFO] Watching for file changes with StatReloader
[2024-06-05 19:21:33][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:21:42][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:22:26][INFO] Watching for file changes with StatReloader
[2024-06-05 19:26:59][INFO] Watching for file changes with StatReloader
[2024-06-05 19:27:08][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:27:08][WARNING] Not Found: /favicon.ico
[2024-06-05 19:29:35][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/logger.py changed, reloading.
[2024-06-05 19:29:35][INFO] Watching for file changes with StatReloader
[2024-06-05 19:31:32][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:33:49][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:33:49][WARNING] Not Found: /favicon.ico
[2024-06-05 19:34:39][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:34:58][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/urls.py changed, reloading.
[2024-06-05 19:34:59][INFO] Watching for file changes with StatReloader
[2024-06-05 19:35:08][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/views.py changed, reloading.
[2024-06-05 19:35:08][INFO] Watching for file changes with StatReloader
[2024-06-05 19:35:11][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 9, in get
    logger.info("Forwarding -> " + CallForwardingRecords.objects.all())
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "QuerySet") to str
[2024-06-05 19:35:11][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 84604
[2024-06-05 19:35:16][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 9, in get
    logger.info("Forwarding -> " + CallForwardingRecords.objects.all())
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "QuerySet") to str
[2024-06-05 19:35:16][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 84604
[2024-06-05 19:35:39][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:35:39][INFO] Watching for file changes with StatReloader
[2024-06-05 19:35:44][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:36:04][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:36:04][INFO] Watching for file changes with StatReloader
[2024-06-05 19:36:33][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:36:33][INFO] Watching for file changes with StatReloader
[2024-06-05 19:36:36][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:36:46][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:36:47][INFO] Watching for file changes with StatReloader
[2024-06-05 19:36:48][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:37:04][INFO] "GET / HTTP/1.1" 200 5529
[2024-06-05 19:37:06][WARNING] Not Found: /favicon.ico
[2024-06-05 19:37:09][INFO] "GET /admin/ HTTP/1.1" 200 11985
[2024-06-05 19:37:09][INFO] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[2024-06-05 19:37:09][INFO] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[2024-06-05 19:37:09][INFO] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2024-06-05 19:37:09][INFO] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2024-06-05 19:37:12][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 10318
[2024-06-05 19:37:12][INFO] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2024-06-05 19:37:12][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:37:12][INFO] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[2024-06-05 19:37:15][INFO] "GET /admin/samj/destinationrecords/ HTTP/1.1" 200 11688
[2024-06-05 19:37:15][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:37:20][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 10318
[2024-06-05 19:37:20][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:37:21][WARNING] Not Found: /favicon.ico
[2024-06-05 19:37:22][INFO] "GET /admin/samj/callforwardingrecords/add/ HTTP/1.1" 200 15065
[2024-06-05 19:37:22][INFO] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:37:22][INFO] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
[2024-06-05 19:37:22][INFO] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[2024-06-05 19:37:22][INFO] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[2024-06-05 19:37:36][INFO] "POST /admin/samj/callforwardingrecords/add/ HTTP/1.1" 302 0
[2024-06-05 19:37:36][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 11931
[2024-06-05 19:37:36][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:37:37][INFO] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[2024-06-05 19:37:42][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:38:10][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:38:10][INFO] Watching for file changes with StatReloader
[2024-06-05 19:38:12][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:38:30][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:38:30][INFO] Watching for file changes with StatReloader
[2024-06-05 19:38:32][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:38:47][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:38:47][INFO] Watching for file changes with StatReloader
[2024-06-05 19:38:49][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.number)
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'number'
[2024-06-05 19:38:49][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85321
[2024-06-05 19:38:54][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.number)
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'number'
[2024-06-05 19:38:54][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85321
[2024-06-05 19:38:56][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.number)
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'number'
[2024-06-05 19:38:56][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85321
[2024-06-05 19:39:05][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:39:06][INFO] Watching for file changes with StatReloader
[2024-06-05 19:39:37][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:39:37][INFO] Watching for file changes with StatReloader
[2024-06-05 19:39:39][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.calledNumber)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'calledNumber'
[2024-06-05 19:39:39][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85369
[2024-06-05 19:39:50][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 11677
[2024-06-05 19:39:50][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:39:51][INFO] "GET /admin/samj/callforwardingrecords/2/change/ HTTP/1.1" 200 15420
[2024-06-05 19:39:51][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:39:56][INFO] "GET /admin/samj/destinationrecords/ HTTP/1.1" 200 11688
[2024-06-05 19:39:56][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:39:57][INFO] "GET /admin/samj/destinationrecords/_2B4369918822211/change/ HTTP/1.1" 200 12090
[2024-06-05 19:39:57][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:39:58][WARNING] Not Found: /favicon.ico
[2024-06-05 19:40:09][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:40:09][INFO] Watching for file changes with StatReloader
[2024-06-05 19:40:11][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.Name)
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'Name'. Did you mean: 'name'?
[2024-06-05 19:40:11][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85305
[2024-06-05 19:40:14][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    logger.info(row.destination.Name)
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'Name'. Did you mean: 'name'?
[2024-06-05 19:40:14][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85305
[2024-06-05 19:40:18][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:40:19][INFO] Watching for file changes with StatReloader
[2024-06-05 19:40:20][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:41:13][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:41:13][INFO] Watching for file changes with StatReloader
[2024-06-05 19:41:16][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    logger.info(row.destination.toString())
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DestinationRecords' object has no attribute 'toString'
[2024-06-05 19:41:16][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85339
[2024-06-05 19:41:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:41:21][INFO] Watching for file changes with StatReloader
[2024-06-05 19:42:41][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:42:41][INFO] Watching for file changes with StatReloader
[2024-06-05 19:42:44][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table.get(0))
                ^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
[2024-06-05 19:42:44][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 118829
[2024-06-05 19:42:45][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table.get(0))
                ^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
[2024-06-05 19:42:45][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 118829
[2024-06-05 19:42:57][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:42:58][INFO] Watching for file changes with StatReloader
[2024-06-05 19:42:59][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table.get(0).destination)
                ^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
[2024-06-05 19:42:59][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 118853
[2024-06-05 19:43:07][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:43:07][INFO] Watching for file changes with StatReloader
[2024-06-05 19:43:08][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:45:35][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:45:35][INFO] Watching for file changes with StatReloader
[2024-06-05 19:45:36][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:46:37][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:46:37][INFO] Watching for file changes with StatReloader
[2024-06-05 19:46:38][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:47:05][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:47:05][INFO] Watching for file changes with StatReloader
[2024-06-05 19:47:07][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:47:36][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:47:37][INFO] Watching for file changes with StatReloader
[2024-06-05 19:47:39][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:49:58][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 11677
[2024-06-05 19:49:58][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:49:59][WARNING] Not Found: /favicon.ico
[2024-06-05 19:50:00][INFO] "GET /admin/samj/callforwardingrecords/2/change/ HTTP/1.1" 200 15420
[2024-06-05 19:50:00][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-05 19:50:32][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:50:33][INFO] Watching for file changes with StatReloader
[2024-06-05 19:51:05][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:51:05][INFO] Watching for file changes with StatReloader
[2024-06-05 19:51:09][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table.filter(CalledNumber="+4367763106443"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'CalledNumber' into field. Choices are: calledNumber, destination, destination_id, endDate, id, startDate, username
[2024-06-05 19:51:09][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 126943
[2024-06-05 19:53:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:53:21][INFO] Watching for file changes with StatReloader
[2024-06-05 19:53:23][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:54:15][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:54:15][INFO] Watching for file changes with StatReloader
[2024-06-05 19:54:17][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table[0]["destination"])
                ~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'CallForwardingRecords' object is not subscriptable
[2024-06-05 19:54:17][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85310
[2024-06-05 19:54:33][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:54:34][INFO] Watching for file changes with StatReloader
[2024-06-05 19:54:35][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:55:09][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:55:10][INFO] Watching for file changes with StatReloader
[2024-06-05 19:55:11][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:55:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:55:21][INFO] Watching for file changes with StatReloader
[2024-06-05 19:55:36][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 10, in get
    logger.info(table[0]["destination"])
                ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'destination'
[2024-06-05 19:55:36][ERROR] "GET /restEndpoint/ HTTP/1.1" 500 85367
[2024-06-05 19:55:49][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:55:50][INFO] Watching for file changes with StatReloader
[2024-06-05 19:55:52][INFO] "GET /restEndpoint/ HTTP/1.1" 200 3
[2024-06-05 19:56:28][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:56:28][INFO] Watching for file changes with StatReloader
[2024-06-05 19:58:10][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:58:10][INFO] Watching for file changes with StatReloader
[2024-06-05 19:58:16][INFO] "GET /restEndpoint/ HTTP/1.1" 200 14
[2024-06-05 19:58:16][WARNING] Not Found: /favicon.ico
[2024-06-05 19:58:32][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:58:32][INFO] Watching for file changes with StatReloader
[2024-06-05 19:58:47][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 19:58:47][INFO] Watching for file changes with StatReloader
[2024-06-05 20:00:59][WARNING] Not Found: /restEndpoint/+4367763106443
[2024-06-05 20:00:59][WARNING] "GET /restEndpoint/+4367763106443 HTTP/1.1" 404 3354
[2024-06-05 20:09:28][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 20:09:28][INFO] Watching for file changes with StatReloader
[2024-06-05 20:10:27][WARNING] Not Found: /restEndpoint/number=+4367763106443
[2024-06-05 20:10:27][WARNING] "GET /restEndpoint/number=+4367763106443 HTTP/1.1" 404 3377
[2024-06-05 20:13:30][INFO] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 200 5
[2024-06-05 20:13:43][INFO] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 200 5
[2024-06-05 20:14:06][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 20:14:06][INFO] Watching for file changes with StatReloader
[2024-06-05 20:14:09][INFO] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 200 5
[2024-06-05 20:14:18][INFO] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 200 5
[2024-06-05 20:14:33][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 20:14:33][INFO] Watching for file changes with StatReloader
[2024-06-05 20:14:37][INFO] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 200 5
[2024-06-05 20:14:53][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-05 20:14:54][INFO] Watching for file changes with StatReloader
[2024-06-05 20:14:56][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-05 20:14:56][ERROR] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 500 126717
[2024-06-17 16:58:47][INFO] Watching for file changes with StatReloader
[2024-06-17 16:59:01][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 16:59:01][ERROR] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 500 126717
[2024-06-17 16:59:34][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 16:59:34][ERROR] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 500 126717
[2024-06-17 16:59:59][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 16:59:59][ERROR] "GET /restEndpoint/?number=+4367763106443 HTTP/1.1" 500 129365
[2024-06-17 17:00:00][WARNING] Not Found: /favicon.ico
[2024-06-17 17:00:43][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:00:43][ERROR] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 500 126717
[2024-06-17 17:00:50][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:00:50][ERROR] "GET /restEndpoint/?number\=+4367763106443 HTTP/1.1" 500 126717
[2024-06-17 17:00:58][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:00:58][ERROR] "GET /restEndpoint/?number=+4367763106443 HTTP/1.1" 500 129365
[2024-06-17 17:00:59][WARNING] Not Found: /favicon.ico
[2024-06-17 17:01:11][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:01:11][ERROR] "GET /restEndpoint/?number=%27+4367763106443%27 HTTP/1.1" 500 129545
[2024-06-17 17:02:16][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:02:16][ERROR] "GET /restEndpoint/?number=+4367763106443 HTTP/1.1" 500 129365
[2024-06-17 17:03:07][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:03:07][ERROR] "GET /restEndpoint/?number=\+4367763106443 HTTP/1.1" 500 129410
[2024-06-17 17:04:55][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:04:55][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 129381
[2024-06-17 17:05:19][INFO] "GET / HTTP/1.1" 200 5529
[2024-06-17 17:05:19][INFO] "GET /static/css/base.css HTTP/1.1" 200 36
[2024-06-17 17:05:19][INFO] "GET /static/css/home.css HTTP/1.1" 200 578
[2024-06-17 17:05:20][INFO] "GET /static/images/samj_logo.png HTTP/1.1" 304 0
[2024-06-17 17:05:20][INFO] "GET /static/images/inactive_feature.webp HTTP/1.1" 304 0
[2024-06-17 17:05:20][WARNING] Not Found: /favicon.ico
[2024-06-17 17:05:23][INFO] "GET /admin/ HTTP/1.1" 200 12385
[2024-06-17 17:05:23][INFO] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
[2024-06-17 17:05:23][INFO] "GET /static/admin/css/base.css HTTP/1.1" 200 21544
[2024-06-17 17:05:23][INFO] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[2024-06-17 17:05:23][INFO] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[2024-06-17 17:05:23][INFO] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[2024-06-17 17:05:23][INFO] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[2024-06-17 17:05:23][INFO] "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
[2024-06-17 17:05:24][INFO] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[2024-06-17 17:05:24][INFO] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2024-06-17 17:05:24][INFO] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2024-06-17 17:05:27][INFO] "GET /admin/samj/destinationrecords/ HTTP/1.1" 200 11688
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:05:27][INFO] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2024-06-17 17:05:27][INFO] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[2024-06-17 17:05:28][INFO] "GET /admin/samj/destinationrecords/_2B4369918822211/change/ HTTP/1.1" 200 12090
[2024-06-17 17:05:28][INFO] "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
[2024-06-17 17:05:28][INFO] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[2024-06-17 17:05:28][INFO] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2024-06-17 17:05:28][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:05:28][INFO] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
[2024-06-17 17:06:48][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:06:48][INFO] Watching for file changes with StatReloader
[2024-06-17 17:06:53][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 13, in get
    logger.info(dest[0]["destination_id"])
                ~~~~^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 452, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-17 17:06:53][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89740
[2024-06-17 17:06:53][WARNING] Not Found: /favicon.ico
[2024-06-17 17:07:43][INFO] "GET /admin/samj/destinationrecords/ HTTP/1.1" 200 11688
[2024-06-17 17:07:43][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:07:44][WARNING] Not Found: /favicon.ico
[2024-06-17 17:08:17][INFO] "GET /admin/samj/destinationrecords/_2B4369918822211/change/ HTTP/1.1" 200 12090
[2024-06-17 17:08:17][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:08:17][WARNING] Not Found: /favicon.ico
[2024-06-17 17:08:29][INFO] "GET /admin/samj/destinationrecords/ HTTP/1.1" 200 11688
[2024-06-17 17:08:29][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:08:29][WARNING] Not Found: /favicon.ico
[2024-06-17 17:08:57][INFO] "GET /admin/samj/callforwardingrecords/ HTTP/1.1" 200 11677
[2024-06-17 17:08:57][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:08:57][WARNING] Not Found: /favicon.ico
[2024-06-17 17:08:58][INFO] "GET /admin/samj/callforwardingrecords/2/change/ HTTP/1.1" 200 15420
[2024-06-17 17:08:58][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:08:58][INFO] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[2024-06-17 17:08:58][INFO] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[2024-06-17 17:08:58][INFO] "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
[2024-06-17 17:08:59][WARNING] Not Found: /favicon.ico
[2024-06-17 17:08:59][INFO] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[2024-06-17 17:09:27][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:09:28][INFO] Watching for file changes with StatReloader
[2024-06-17 17:09:30][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 13, in get
    logger.info(dest[0]["destination_id"])
                ~~~~^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 452, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-17 17:09:30][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89747
[2024-06-17 17:10:10][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:10:10][INFO] Watching for file changes with StatReloader
[2024-06-17 17:10:13][INFO] "GET /admin/samj/callforwardingrecords/2/change/ HTTP/1.1" 200 15420
[2024-06-17 17:10:13][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:10:13][WARNING] Not Found: /favicon.ico
[2024-06-17 17:10:26][INFO] "GET /admin/samj/callforwardingrecords/2/change/ HTTP/1.1" 200 15420
[2024-06-17 17:10:26][INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2024-06-17 17:10:31][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    logger.info("objects -> " + CallForwardingRecords.objects.all())
                ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "QuerySet") to str
[2024-06-17 17:10:31][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 86107
[2024-06-17 17:10:32][WARNING] Not Found: /favicon.ico
[2024-06-17 17:10:55][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:10:55][INFO] Watching for file changes with StatReloader
[2024-06-17 17:11:01][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:11:02][INFO] Watching for file changes with StatReloader
[2024-06-17 17:11:03][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 13, in get
    dest = CallForwardingRecords.objects.all().filter(destination_id__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:11:03][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 129506
[2024-06-17 17:11:04][WARNING] Not Found: /favicon.ico
[2024-06-17 17:15:27][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:15:27][INFO] Watching for file changes with StatReloader
[2024-06-17 17:15:29][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 14, in get
    logger.info(dest[0])
                ~~~~^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 452, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-17 17:15:29][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89752
[2024-06-17 17:15:29][WARNING] Not Found: /favicon.ico
[2024-06-17 17:15:57][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:15:58][INFO] Watching for file changes with StatReloader
[2024-06-17 17:15:59][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 14, in get
    logger.info("info: " + dest[0])
                           ~~~~^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 452, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-17 17:15:59][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89816
[2024-06-17 17:15:59][WARNING] Not Found: /favicon.ico
[2024-06-17 17:16:03][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 14, in get
    logger.info("info: " + dest[0])
                           ~~~~^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 452, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-17 17:16:03][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89816
[2024-06-17 17:16:03][WARNING] Not Found: /favicon.ico
[2024-06-17 17:16:23][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:16:23][INFO] Watching for file changes with StatReloader
[2024-06-17 17:16:27][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 14, in get
    logger.info("info: " + dest[0])
                ~~~~~~~~~^~~~~~~~~
TypeError: can only concatenate str (not "dict") to str
[2024-06-17 17:16:27][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 86123
[2024-06-17 17:16:39][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:16:39][INFO] Watching for file changes with StatReloader
[2024-06-17 17:16:40][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 14, in get
    logger.info("info: " + dest)
                ~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "QuerySet") to str
[2024-06-17 17:16:40][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 86127
[2024-06-17 17:16:40][WARNING] Not Found: /favicon.ico
[2024-06-17 17:17:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:17:21][INFO] Watching for file changes with StatReloader
[2024-06-17 17:17:30][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:17:30][INFO] Watching for file changes with StatReloader
[2024-06-17 17:17:32][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    dest = CallForwardingRecords.objects.all().filter(destination__icontains=query).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
[2024-06-17 17:17:32][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 129246
[2024-06-17 17:17:33][WARNING] Not Found: /favicon.ico
[2024-06-17 17:17:43][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:17:43][INFO] Watching for file changes with StatReloader
[2024-06-17 17:17:49][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:17:49][INFO] Watching for file changes with StatReloader
[2024-06-17 17:17:50][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    dest = CallForwardingRecords.objects.all().filter(source_number=query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'source_number' into field. Choices are: calledNumber, destination, destination_id, endDate, id, startDate, username
[2024-06-17 17:17:50][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 127327
[2024-06-17 17:17:50][WARNING] Not Found: /favicon.ico
[2024-06-17 17:19:05][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:19:06][INFO] Watching for file changes with StatReloader
[2024-06-17 17:19:30][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    logger.info(dest[0]["destination_id"])
                ~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'CallForwardingRecords' object is not subscriptable
[2024-06-17 17:19:30][ERROR] "GET /restEndpoint/?number\=%2B4367763106443 HTTP/1.1" 500 83230
[2024-06-17 17:20:03][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:20:04][INFO] Watching for file changes with StatReloader
[2024-06-17 17:20:27][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:20:27][INFO] Watching for file changes with StatReloader
[2024-06-17 17:20:28][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 3
[2024-06-17 17:20:28][WARNING] Not Found: /favicon.ico
[2024-06-17 17:21:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:21:21][INFO] Watching for file changes with StatReloader
[2024-06-17 17:21:23][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 3
[2024-06-17 17:21:56][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:21:56][INFO] Watching for file changes with StatReloader
[2024-06-17 17:21:57][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 3
[2024-06-17 17:21:57][WARNING] Not Found: /favicon.ico
[2024-06-17 17:22:03][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 3
[2024-06-17 17:22:03][WARNING] Not Found: /favicon.ico
[2024-06-17 17:23:55][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:23:55][INFO] Watching for file changes with StatReloader
[2024-06-17 17:24:04][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:24:04][INFO] Watching for file changes with StatReloader
[2024-06-17 17:24:10][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().values().filter(calledNumber=query)["destination_id"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 420, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2024-06-17 17:24:10][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89988
[2024-06-17 17:24:11][WARNING] Not Found: /favicon.ico
[2024-06-17 17:24:22][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:24:22][INFO] Watching for file changes with StatReloader
[2024-06-17 17:24:22][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 12, in get
    dest = CallForwardingRecords.objects.all().values().filter(calledNumber=query)["destination_id"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/db/models/query.py", line 420, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2024-06-17 17:24:22][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 89999
[2024-06-17 17:24:22][WARNING] Not Found: /favicon.ico
[2024-06-17 17:24:41][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:24:42][INFO] Watching for file changes with StatReloader
[2024-06-17 17:24:44][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 3
[2024-06-17 17:24:44][WARNING] Not Found: /favicon.ico
[2024-06-17 17:27:24][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:27:25][INFO] Watching for file changes with StatReloader
[2024-06-17 17:27:30][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:27:56][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:27:56][INFO] Watching for file changes with StatReloader
[2024-06-17 17:27:57][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:27:57][WARNING] Not Found: /favicon.ico
[2024-06-17 17:28:05][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:28:05][ERROR] "GET /restEndpoint/?number\=%2B4367763106443 HTTP/1.1" 500 83217
[2024-06-17 17:28:15][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:28:15][WARNING] Not Found: /favicon.ico
[2024-06-17 17:28:28][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:28:28][ERROR] "GET /restEndpoint/?number\=%2B4367763106443 HTTP/1.1" 500 83217
[2024-06-17 17:28:41][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:28:47][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:28:59][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:29:03][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:29:03][ERROR] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 500 83197
[2024-06-17 17:29:06][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:29:06][ERROR] "GET /restEndpoint/?number=%2B4367763 HTTP/1.1" 500 83147
[2024-06-17 17:29:12][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:29:12][ERROR] "GET /restEndpoint/?number=%2B4367763 HTTP/1.1" 500 83147
[2024-06-17 17:29:15][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:29:15][ERROR] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 500 83197
[2024-06-17 17:29:19][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 15, in get
    logger.info(dest["destination_id"])
                ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:29:19][ERROR] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 500 83197
[2024-06-17 17:29:22][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:31:21][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:31:21][INFO] Watching for file changes with StatReloader
[2024-06-17 17:31:23][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:31:29][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 18, in get
    return HttpResponse(dest["destination_id"])
                        ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-17 17:31:29][ERROR] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 500 82973
[2024-06-17 17:31:48][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:31:48][INFO] Watching for file changes with StatReloader
[2024-06-17 17:31:49][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 17:33:02][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 17:33:25][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 17:33:28][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:33:36][INFO] "GET /restEndpoint/?number='%2B4367763106443' HTTP/1.1" 200 5
[2024-06-17 17:34:36][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:34:36][INFO] Watching for file changes with StatReloader
[2024-06-17 17:34:38][INFO] "GET /restEndpoint/?number='%2B4367763106443' HTTP/1.1" 200 6
[2024-06-17 17:34:42][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:34:47][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 6
[2024-06-17 17:34:53][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:34:53][INFO] Watching for file changes with StatReloader
[2024-06-17 17:38:37][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:38:38][INFO] Watching for file changes with StatReloader
[2024-06-17 17:38:59][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:38:59][INFO] Watching for file changes with StatReloader
[2024-06-17 17:39:08][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:39:09][INFO] Watching for file changes with StatReloader
[2024-06-17 17:39:32][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:39:32][INFO] Watching for file changes with StatReloader
[2024-06-17 17:39:52][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:39:53][INFO] Watching for file changes with StatReloader
[2024-06-17 17:39:56][ERROR] Internal Server Error: /restEndpoint/
Traceback (most recent call last):
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py", line 11, in get
    dest = getDest(query)
           ^^^^^^^
NameError: name 'getDest' is not defined
[2024-06-17 17:39:56][ERROR] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 500 85554
[2024-06-17 17:39:56][WARNING] Not Found: /favicon.ico
[2024-06-17 17:40:08][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-17 17:40:08][INFO] Watching for file changes with StatReloader
[2024-06-17 17:40:10][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 17:40:14][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:16:03][INFO] Watching for file changes with StatReloader
[2024-06-17 18:18:34][INFO] Watching for file changes with StatReloader
[2024-06-17 18:18:59][INFO] Watching for file changes with StatReloader
[2024-06-17 18:38:07][INFO] Watching for file changes with StatReloader
[2024-06-17 18:38:26][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:38:31][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 18:41:44][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-17 18:41:51][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:45:57][INFO] Watching for file changes with StatReloader
[2024-06-17 18:46:06][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:51:00][INFO] Watching for file changes with StatReloader
[2024-06-17 18:51:03][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:52:15][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-17 18:52:15][INFO] Watching for file changes with StatReloader
[2024-06-17 18:52:17][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:54:48][INFO] Watching for file changes with StatReloader
[2024-06-17 18:54:51][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:54:55][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-17 18:54:56][INFO] Watching for file changes with StatReloader
[2024-06-17 18:54:57][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-17 18:56:59][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-17 18:56:59][INFO] Watching for file changes with StatReloader
[2024-06-18 17:04:16][INFO] Watching for file changes with StatReloader
[2024-06-18 17:04:23][INFO] "GET / HTTP/1.1" 200 5529
[2024-06-18 17:04:25][WARNING] Not Found: /favicon.ico
[2024-06-18 17:05:11][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-18 17:05:18][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-18 17:06:31][INFO] "GET /restEndpoint/?number=%2B436776310644 HTTP/1.1" 200 5
[2024-06-18 17:06:43][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-18 17:07:34][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-18 17:07:35][INFO] Watching for file changes with StatReloader
[2024-06-18 17:07:38][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-18 17:18:57][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samj/viewClasses/restEndpoint.py changed, reloading.
[2024-06-18 17:18:57][INFO] Watching for file changes with StatReloader
[2024-06-18 17:20:02][INFO] /home/schwerti/Documents/GitHub/SAMJ-CSDC26BB/SAMJ-Django-TBC/samjTBC/samjTBC/settings.py changed, reloading.
[2024-06-18 17:20:02][INFO] Watching for file changes with StatReloader
[2024-06-18 17:20:15][INFO] "GET /restEndpoint/?number=%2B4367763106443 HTTP/1.1" 200 14
[2024-06-19 12:53:06][INFO] Watching for file changes with StatReloader
[2024-06-19 12:54:29][INFO] Watching for file changes with StatReloader
[2024-06-19 12:55:44][INFO] Watching for file changes with StatReloader
[2024-06-19 12:59:49][INFO] Watching for file changes with StatReloader
[2024-06-19 13:01:04][INFO] Watching for file changes with StatReloader
[2024-06-19 13:01:37][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\urls.py changed, reloading.
[2024-06-19 13:01:37][INFO] Watching for file changes with StatReloader
[2024-06-19 13:09:00][INFO] Watching for file changes with StatReloader
[2024-06-19 13:09:02][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:09:02][INFO] "GET /static/css/base.css HTTP/1.1" 304 0
[2024-06-19 13:09:02][INFO] "GET /static/css/home.css HTTP/1.1" 304 0
[2024-06-19 13:09:03][INFO] "GET /static/images/samj_logo.png HTTP/1.1" 304 0
[2024-06-19 13:09:03][INFO] "GET /static/images/inactive_feature.webp HTTP/1.1" 304 0
[2024-06-19 13:09:03][WARNING] Not Found: /favicon.ico
[2024-06-19 13:09:03][INFO] - Broken pipe from ('127.0.0.1', 61910)
[2024-06-19 13:09:21][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:09:24][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:09:24][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:10:37][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
[2024-06-19 13:10:37][INFO] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2024-06-19 13:16:56][INFO] Watching for file changes with StatReloader
[2024-06-19 13:17:12][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samjTBC\settings.py changed, reloading.
[2024-06-19 13:17:12][INFO] Watching for file changes with StatReloader
[2024-06-19 13:17:14][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:17:15][WARNING] Not Found: /favicon.ico
[2024-06-19 13:17:15][INFO] - Broken pipe from ('127.0.0.1', 62113)
[2024-06-19 13:17:26][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samjTBC\settings.py changed, reloading.
[2024-06-19 13:17:26][INFO] Watching for file changes with StatReloader
[2024-06-19 13:17:49][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samjTBC\settings.py changed, reloading.
[2024-06-19 13:17:49][INFO] Watching for file changes with StatReloader
[2024-06-19 13:17:53][INFO] Watching for file changes with StatReloader
[2024-06-19 13:25:04][INFO] Watching for file changes with StatReloader
[2024-06-19 13:25:07][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:25:12][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:36:27][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 13:36:31][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:36:36][INFO] "OPTIONS /api_schema HTTP/1.1" 200 5632
[2024-06-19 13:36:39][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:36:40][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:36:43][INFO] "OPTIONS /api_schema HTTP/1.1" 200 5632
[2024-06-19 13:36:44][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 13:56:08][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\urls.py changed, reloading.
[2024-06-19 13:56:09][INFO] Watching for file changes with StatReloader
[2024-06-19 14:18:21][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\urls.py changed, reloading.
[2024-06-19 14:18:21][INFO] Watching for file changes with StatReloader
[2024-06-19 14:20:58][INFO] Watching for file changes with StatReloader
[2024-06-19 14:34:46][INFO] Watching for file changes with StatReloader
[2024-06-19 14:35:18][INFO] Watching for file changes with StatReloader
[2024-06-19 14:35:44][INFO] Watching for file changes with StatReloader
[2024-06-19 14:36:46][INFO] Watching for file changes with StatReloader
[2024-06-19 14:37:03][INFO] Watching for file changes with StatReloader
[2024-06-19 14:38:32][INFO] Watching for file changes with StatReloader
[2024-06-19 14:38:36][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:38:57][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:39:03][INFO] "GET /api_schema HTTP/1.1" 200 5531
[2024-06-19 14:39:15][INFO] "GET /swagger-ui HTTP/1.1" 301 0
[2024-06-19 14:39:15][INFO] "GET /swagger-ui/ HTTP/1.1" 200 682
[2024-06-19 14:41:25][INFO] "GET /swagger-ui/ HTTP/1.1" 200 682
[2024-06-19 14:46:39][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:46:46][ERROR] Internal Server Error: /swagger-ui/
Traceback (most recent call last):
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\myenv\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'rest-endpoint' not found. 'rest-endpoint' is not a valid view function or pattern name.
[2024-06-19 14:46:46][ERROR] "GET /swagger-ui/ HTTP/1.1" 500 120931
[2024-06-19 14:47:34][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\urls.py changed, reloading.
[2024-06-19 14:47:34][INFO] Watching for file changes with StatReloader
[2024-06-19 14:48:03][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:48:03][INFO] Watching for file changes with StatReloader
[2024-06-19 14:48:46][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:48:47][INFO] Watching for file changes with StatReloader
[2024-06-19 14:49:11][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:49:12][INFO] Watching for file changes with StatReloader
[2024-06-19 14:49:38][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:49:38][INFO] Watching for file changes with StatReloader
[2024-06-19 14:50:08][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:50:08][INFO] Watching for file changes with StatReloader
[2024-06-19 14:51:03][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:54:39][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:54:39][INFO] "GET /static/css/home.css HTTP/1.1" 304 0
[2024-06-19 14:54:39][INFO] "GET /static/css/base.css HTTP/1.1" 200 69
[2024-06-19 14:54:39][INFO] "GET /static/images/samj_logo.png HTTP/1.1" 304 0
[2024-06-19 14:54:39][INFO] "GET /static/images/inactive_feature.webp HTTP/1.1" 304 0
[2024-06-19 14:54:59][INFO] "GET /api/endpoint HTTP/1.1" 301 0
[2024-06-19 14:54:59][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 14:56:14][INFO] Watching for file changes with StatReloader
[2024-06-19 14:56:16][INFO] "GET / HTTP/1.1" 200 5583
[2024-06-19 14:57:05][INFO] "GET /swagger-ui/ HTTP/1.1" 200 691
[2024-06-19 14:57:05][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 14:59:26][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 14:59:26][INFO] Watching for file changes with StatReloader
[2024-06-19 14:59:29][INFO] "GET /swagger-ui/ HTTP/1.1" 200 872
[2024-06-19 14:59:29][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:03:59][INFO] "GET /swagger-ui/ HTTP/1.1" 200 872
[2024-06-19 15:03:59][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:07:16][INFO] "GET /swagger-ui/ HTTP/1.1" 200 949
[2024-06-19 15:07:16][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:07:21][INFO] "GET /swagger-ui/ HTTP/1.1" 200 949
[2024-06-19 15:07:21][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:07:30][INFO] Watching for file changes with StatReloader
[2024-06-19 15:09:15][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:09:16][INFO] Watching for file changes with StatReloader
[2024-06-19 15:09:26][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:09:26][INFO] Watching for file changes with StatReloader
[2024-06-19 15:09:30][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:09:30][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:10:23][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:10:23][INFO] Watching for file changes with StatReloader
[2024-06-19 15:10:28][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:10:28][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:10:49][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:10:49][INFO] Watching for file changes with StatReloader
[2024-06-19 15:10:52][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:10:52][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:18:05][INFO] Watching for file changes with StatReloader
[2024-06-19 15:18:10][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:18:10][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:18:55][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:18:55][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:21:38][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:21:39][INFO] Watching for file changes with StatReloader
[2024-06-19 15:21:43][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:21:43][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:21:50][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:21:50][WARNING] Not Found: /favicon.ico
[2024-06-19 15:21:50][WARNING] "GET /favicon.ico HTTP/1.1" 404 4036
[2024-06-19 15:21:50][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:24:36][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:24:36][INFO] Watching for file changes with StatReloader
[2024-06-19 15:24:39][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:24:39][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:24:56][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:24:56][INFO] Watching for file changes with StatReloader
[2024-06-19 15:27:24][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:27:24][INFO] Watching for file changes with StatReloader
[2024-06-19 15:27:41][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:27:41][INFO] Watching for file changes with StatReloader
[2024-06-19 15:27:42][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:27:42][WARNING] Not Found: /favicon.ico
[2024-06-19 15:27:42][WARNING] "GET /favicon.ico HTTP/1.1" 404 4036
[2024-06-19 15:27:42][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:27:43][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:27:43][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:27:43][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:27:43][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:27:44][WARNING] Not Found: /favicon.ico
[2024-06-19 15:27:44][WARNING] "GET /favicon.ico HTTP/1.1" 404 4036
[2024-06-19 15:27:44][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
[2024-06-19 15:30:48][INFO] C:\Users\Joni\PycharmProjects\SAMJ-Django-TBC\samjTBC\samj\views.py changed, reloading.
[2024-06-19 15:30:48][INFO] Watching for file changes with StatReloader
[2024-06-19 15:30:51][INFO] "GET /swagger-ui/ HTTP/1.1" 200 898
[2024-06-19 15:30:51][INFO] "GET /api/endpoint/ HTTP/1.1" 200 5
